/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.7/samples
 */

plugins {
    id("jacoco")
    id("java-gradle-plugin")
    id("com.gradle.plugin-publish") version "1.2.1"
    id("org.jetbrains.kotlin.jvm") version("1.9.10")
}

version = "0.6.0"
group = "com.fussionlabs.gradle"

repositories {
    mavenLocal()
    mavenCentral()
}

kotlin {
    jvmToolchain {
        languageVersion.set(JavaLanguageVersion.of(JavaVersion.VERSION_1_8.majorVersion))
    }
}

dependencies {
    testImplementation(platform("org.junit:junit-bom:5.10.1"))
    testImplementation("org.junit.jupiter:junit-jupiter")
}

tasks.test {
    useJUnitPlatform()
    finalizedBy(tasks.jacocoTestReport)
}

tasks.jacocoTestReport {
    reports {
        html.required = true
    }
}

gradlePlugin {
    website = "https://github.com/dm0275/docker-plugin"
    vcsUrl = "https://github.com/dm0275/docker-plugin.git"
    plugins {
        create("docker-plugin") {
            id = "com.fussionlabs.gradle.docker-plugin"
            displayName = "Docker Gradle plugin"
            implementationClass = "com.fussionlabs.gradle.docker.DockerPlugin"
            tags = listOf("docker")
            description = "The `docker-plugin` is a Gradle plugin created to simplify the process of building and " +
                    "pushing Docker images. It calls the Docker CLI directly, supports multiplatform builds and " +
                    "provides the ability to define custom Docker tasks."
        }
    }
}